% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Projekt nr 5},
  pdfauthor={Anna Herud},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Projekt nr 5}
\author{Anna Herud}
\date{10 06 2021}

\begin{document}
\maketitle

\hypertarget{cel-projektu}{%
\section{Cel projektu}\label{cel-projektu}}

Celem projektu jest analiza danych chorych na raka części ustnej gardła,
porównując czas przeżycia pacjentów leczonych radioterapią lub
radioterapią i chemioterapią. W projekcie przeanalizowany zostanie wpływ
różnych zmiennych na czas przeżycia chorych oraz dopasowany zostanie
model Coxa oraz model ATF.

\hypertarget{wstux119pna-analiza-zbioru-danych}{%
\section{Wstępna analiza zbioru
danych}\label{wstux119pna-analiza-zbioru-danych}}

Dane wykorzystane w projekcie składają się z \(195\) obserwacji. Zmienna
która nas interesuje, to zmienna \texttt{TIME}, czyli czas przeżycia
pacjenta od chwili diagnozy. Najkrótszy czas przeżycia to \(11\) dni, a
mediana szacowna estymatorem Kaplana - Meiera to \(461\) dni. Jest to
jest najkrótszym, zaobserwowanym czasem zdarzenia, dla którego
\(S(t) < 50 \%.\)

Zmienna \texttt{STATUS} jest w naszym zbiorze danych indykatorem czasów
cenzurowanych. Pacjentów, którzy nie zmarli w okresie prowadzonych
obserwacji, uznajemy jako obserwacje cenzurowane. Około \(27\%\) danych,
to obserwacje cenzurowane.

Zmienne, których wpływ na czas przeżycia pacjentów chorych na raka, to:

\begin{itemize}
\tightlist
\item
  \texttt{SEX}: płeć pacjenta (ok. \(76\%\) mężczyzn i ok. \(24\%\)
  kobiet)
\item
  \texttt{GRADE}: stopień zróżnicowania nowotworu (1 obserwacja nie
  zawierająca danych, dla pozostałych: ok. \(26\%\) pacjentów o wysokim
  zróżnicowaniu nowotworu, ok. \(56\%\) o średnim zróżnicowaniu oraz ok.
  \(18\%\) procent o niskim stopniu zróżnicowania)
\item
  \texttt{TX}: leczenie (ok. \(51\%\) pacjentów poddanych zostało
  radioterapii, a \(49\%\) pacjentów poddanych zostało radioterapii i
  chemioterapii)
\item
  \texttt{AGE}: wiek w latach w chwili diagnozy
\item
  \texttt{COND}: stopień sprawności chorego (2 obserwacje nie zwierają
  danych, dla pozostałych: ok. \(74\%\) pacjentów nie ma ograniczonej
  sprawności, ok. \(22\%\) ma ograniczoną sprawność w pracy, ok. \(3\%\)
  pacjentów wymaga częściowej opieki i 1 pacjent wymaga całkowitej
  opieki)
\item
  \texttt{SITE}: lokalizacja guza (w przypadku ok. \(33\%\) pacjentów
  guz znajduje się na łuku podniebiennym, podobnie dla lokalizacji guza
  w dole migdałkowym, ok. \(34\%\) pacjentów posiada guza w nasadzie
  języka)
\item
  \texttt{T\_STAGE}: wielkość guza (ok. \(5\%\) pacjentów posiada guza o
  wielkości \(2\) cm lub mniej, ok. \(13\%\) o wielkości \(2-4\) cm, ok.
  \(48\%\) o wielkości większej niż \(4\) cm, a ok. \(23\%\) pacjentów
  posiada masywnego guza z naciskiem na okoliczne tkanki)
\item
  \texttt{N\_STAGE}: przerzuty do węzłów chłonnych (\(20\%\) pacjentów
  nie ma przerzutów, ok. \(14\%\) ma jeden zajęty węzeł mniejszy niż
  \(3\) cm - ruchomy, ok. \(19\%\) pacjentów ma jeden zajęty węzeł
  większy niż \(3\) cm - ruchomy, ok \(47\%\) pacjentów ma kilka
  zajętych węzłów)
\end{itemize}

Obserwacje dla których występują braku danych w zmiennej \texttt{GRADE}
oraz \texttt{COND} zostaną usunięte.

\hypertarget{wpux142yw-wybranych-zmiennych-na-funkcjux119-przeux17cycia}{%
\section{Wpływ wybranych zmiennych na funkcję
przeżycia}\label{wpux142yw-wybranych-zmiennych-na-funkcjux119-przeux17cycia}}

W pierwszej części zbadany zostanie wpływ zmiennych \texttt{SEX},
\texttt{N\_STAGE} oraz \texttt{T\_STAGE} na prawdopodobieństwo przeżycia
pacjenta.

\hypertarget{wpux142yw-pux142ci-na-prawdopodobieux144stwo-przeux17cycia}{%
\subsubsection{Wpływ płci na prawdopodobieństwo
przeżycia}\label{wpux142yw-pux142ci-na-prawdopodobieux144stwo-przeux17cycia}}

W pierwszej kolejności zbadana zostanie zmienna \texttt{SEX} składająca
się z dwóch poziomów. Na poniższym wykresie została przedstawiona
funkjca prawdopodobieństwa przeżycia dla każdej płci osbno:

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-5-1.pdf}

Na wykresie widać, że przedziały ufności krzywych przeżycia się
pokrywają a same krzywe są dość blisko siebie. Krzywe przecinają się na
początku i końcu wykresu, dlatego aby sprawdzić, czy prawdopodobieństwa
przeżycia dla mężczyzn i dla kobiet się różnią istotnie zastosujemy test
Renyiego, używając wag \(W(t) = 1\). Testujemy następującą hipotezę:

\(H_0: \lambda_{1}(t)=\lambda_{2}(t)\)

\(H_1:\lambda_{1}(t)\neq \lambda_{2}(t)\)

gdzie \(\lambda_{1}(t)\) to funkcja hazardu dla kobiet, a
\(\lambda_{2}(t)\) to funkcja hazardu dla mężczyzn.

{[}1{]} ``P-value testu: 0.27257''

Otrzymaliśmy duże p-value, nie odrzucamy zatem hipotezy zerowej i
zakładamy, że zmienna \texttt{SEX} nie ma wpływu na prawdopodobieństwo
przeżycia.

\hypertarget{wpux142yw-wielkoux15bci-guza-na-prawdopodobieux144stwo-przeux17cycia}{%
\subsubsection{Wpływ wielkości guza na prawdopodobieństwo
przeżycia}\label{wpux142yw-wielkoux15bci-guza-na-prawdopodobieux144stwo-przeux17cycia}}

Po narysowaniu funkcji prawdopodobieństwa przeżycia dla 4 poziomów,
krzywa dla poziomu pierwszego (guz wielkości mniejszej niż 2 cm)
przecina pozostałe krzywe i wygląda dość nieintuicyjnie. Zmienna
`T\_STAGE' dla poziomu \(1\) zawiera jedynie \(5\%\) obserwacji.
Obserwacje z tego poziomu zostaną dołączone do poziomu drugiego, czyli
guzów wielkości 2-4 cm. Wykres prawdopodobieństwa przeżycia dla każdej
kategorii wielkości guza:

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-9-1.pdf}

Przedziały ufności funkjci przeżycia się pokrywają, a proste są zbliżone
do siebie. Trudno jednak po samym wykresie stwierdzić, czy wielkość guza
wpływa na prawdopodobieństwo przeżycia. W celu zweryfikowania hipotezy
zostanie przeprowadzony test trendu. Badana hipoteza:
\(H_0: \lambda_{1}(t)=\lambda_{2}(t) = \lambda_{3}(t)\)

\(H_1:\lambda_{1}(t)\leq \lambda_{3}(t) \leq \lambda_{4}(t)\).

\(\lambda_{i}\) oznacza funkcję hazardu dla \(i\)-tej kategorii dla
\(i=2, 3,4\).

Wartość statystyki testowej:

{[}1{]} ``P-value testu: 0.00278''

Małe p-value odrzuca hipotezę zerową. Zmienna \texttt{T\_SATGE} ma wpływ
na prawdopodobieństwo przeżycia. W szczególności, dla mniejszego guzu
mamy większe prawdopodobieństwo przeżycia. Skoro wiemy, że zmienna
\texttt{T\_STAGE} wpływa na czas przeżycia, sprawdzimy również wpływ
zmiennej \texttt{TX}, czyli rodzaju leczenia, na czas przeżycia w każdej
z warstw zmiennej \texttt{T\_STAGE}.

{[}1{]} ``P-value testu: 0.2337''

Duże p-value wskazuje na to, że nie ma istotnych różnic pomiędzy czasem
przeżycia ze względu na stosowanie różnych rodzai terapii dla różnych
wielkości guza.

\hypertarget{wpux142yw-przerzutuxf3w-do-wux119zux142uxf3w-chux142onnych-na-prawdopodobieux144stwo-przeux17cycia}{%
\subsubsection{Wpływ przerzutów do węzłów chłonnych na
prawdopodobieństwo
przeżycia}\label{wpux142yw-przerzutuxf3w-do-wux119zux142uxf3w-chux142onnych-na-prawdopodobieux144stwo-przeux17cycia}}

Po narysowaniu funkcji przeżycia dla czterech poziomów zmiennej
\texttt{N\_STAGE} okazało się że krzywe dla poziomów \(2\) oraz \(3\)
leżą bardzo blisko siebie. Obie z tych kategorii zawierają również mało
obserwacji, zostaną one zatem połączone.

Funkcje przeżycia dla trzech powstałych poziomów:

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-14-1.pdf}

Według wykresu wydaje się, że ilość węzłów z przerzutami ma wpływ na
prawdopodobieństwo przeżycia, w szczególności pacjenci z 1 węzłem z
przerzutami mają większe prawdopodobieństwo przeżycia niż pozostali
pacjenci. W celu potwierdzenia tej intuicji przeprowadzony zostanie test
log-rank:

\(H_0:\lambda_{1}(t)=\dots=\lambda_{k}(t)\)

\(H_1:\lambda_{i}(t)\neq\lambda_{j}(t)\)

dla pewnych \(i\), \(j \in \{0, 2, 3\}\) .

{[}1{]} ``P-value: 0.00636''

Małe p-value odrzuca hipotezę zerową o równości prawdopodobieństw
przeżycia dla każdego z poziomu zmiennej \texttt{N\_STAGE}. Podobnie jak
w przypadku poprzedniej zmiennej, sprawdzimy czy po warstwowaniu można
zauważyć różnice we wpływie wyboru terapii na prawdopodobieństwo
przeżycia dla różnych liczb węzłów z przerzutami.

{[}1{]} ``P-value testu: 0.315''

Podobnie jak w przypadku zmiennej \texttt{T\_STAGE}, nie ma istotnych
różnic pomiędzy wpływem rodzaju zastosowanej terapii na czas przeżycia w
różnych grupach pacjentów o różnej ilości węzłów chłonnych z
przerzutami.

\hypertarget{model-coxa-proporcjonalnych-hazarduxf3w}{%
\section{Model Coxa proporcjonalnych
hazardów}\label{model-coxa-proporcjonalnych-hazarduxf3w}}

W celu dalszej analizy wpływu zmiennych na czas przeżycia pacjentów,
dopasowany zostanie model Coxa proporcjonalnych hazardów.

\hypertarget{dobuxf3r-zmiennych}{%
\subsubsection{Dobór zmiennych}\label{dobuxf3r-zmiennych}}

Zanim dopasowany zostanie pełny model, ze wszystkimi zmiennymi
objaśniającymi, w zmiennej \texttt{COND} usunięty zostanie jeden poziom.
Dla \texttt{COND\ =\ 4} występuje jedynie jedna obserwacja.
Klasyfikujemy ją do klasy \(3\), osoby wymagające częściowej opieki i
pełnej opieki będą teraz tak samo oznaczane.

Wynik \texttt{summary} dla pełnego modelu zwraca informację o tym, że
większość zmiennych nie jest istotna statystycznie, według testu Walda.
Selekcji zmiennych dokonamy za pomocą kryterium AIC.

Dopasowany model zawiera następujące zmienne:

\begin{longtable}[]{@{}lrrrrr@{}}
\toprule
& coef & exp(coef) & se(coef) & z &
Pr(\textgreater\textbar z\textbar) \\
\midrule
\endhead
SEX2 & -0.3816394 & 0.6827412 & 0.2110178 & -1.8085652 & 0.0705186 \\
COND2 & 1.1570309 & 3.1804759 & 0.2077150 & 5.5702816 & 0.0000000 \\
COND3 & 1.9384251 & 6.9477999 & 0.4393242 & 4.4122886 & 0.0000102 \\
T\_STAGE3 & -0.0707697 & 0.9316764 & 0.2564108 & -0.2760014 &
0.7825470 \\
T\_STAGE4 & 0.4755666 & 1.6089256 & 0.2595973 & 1.8319396 & 0.0669604 \\
\bottomrule
\end{longtable}

Według testu Walda mamy zmienne nieistotne statystycznie, lecz na razie
pozostawimy je w modelu.

Wybrane zmienne to: \texttt{SEX}, \texttt{COND} i \texttt{T\_STAGE}.

\hypertarget{diagnostyka}{%
\subsubsection{Diagnostyka}\label{diagnostyka}}

Przejdźmy teraz do diagnostyki naszego modelu. Kluczowym założeniem
naszego modelu jest proporcjonalność hazardów. Pierwszym narzędziem,
użytym w celu sprawdzenia tego założenia, będzie wykres residuów typu
deviance.

W modelu, w którym założenie o proporcjonalnych hazardach jest spełnione
wykres funkcji jest prostą zbliżoną do prostej na poziomie zera. Na
wykresie dla naszych danych prosta odchyla się nieznacznie od zera. Jej
odchylenie lub kształt może sugerować uwzględnienie pewnej zależności od
czasu w modelu. W naszym przypadku wszystkie wybrane zmienne są
kategoryczne, dlatego nie będziemy analizować wykresów diagnostycznych
pod tym kątem. Z tego samego powodu pominięta zostanie diagnostyka za
pomocą reszt Schoenfelda, które badają niezależność residuów (a zatem i
zmiennych ciągłych) od czasu.

Przeprowadzony zostanie formalny test Schoenfelda, badający spełnienie
założenia o proporcjonalności hazardów dla każdej ze zmiennych w modelu.

\begin{verbatim}
      chisq df     p
\end{verbatim}

SEX 0.0126 1 0.911 COND 9.0332 2 0.011 T\_STAGE 3.8241 2 0.148 GLOBAL
11.6894 5 0.039

\begin{longtable}[]{@{}lrrr@{}}
\toprule
& chisq & df & p \\
\midrule
\endhead
SEX & 0.0125701 & 1 & 0.9107310 \\
COND & 9.0331850 & 2 & 0.0109262 \\
T\_STAGE & 3.8241447 & 2 & 0.1477738 \\
GLOBAL & 11.6894228 & 5 & 0.0393003 \\
\bottomrule
\end{longtable}

Wynik p-value testu mówi nam o tym, że założenie o proporcjonalności
hazardu nie jest spełnione. Główny problem występuje w przypadku
zmiennej \texttt{COND}. Zanim sprawdzone zostaną rozwiązania problemu
przeanalizowany zostanie wykres reszty typu dfbeta w celu detekcji
ewentualnych obserwacji wpływowych:

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-22-1.pdf}

Wykres nie wydaje się wskazywać na obserwacje, które jednoznacznie można
zakwalifikować jako wpływowe.

W celu identyfikacji obserwacji odstających posłużymy się wykresem
rezyduów typu deviance:

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-23-1.pdf}

Residua są rozmieszczone równomiernie wokół zera, żadna z obserwacji
wyraźnie nie odstaje, zakładamy zatem, że nie mamy obserwacji, którą
należałoby usunąć jako odstającą.

Problem niespełnienia założeń o proporcjonalnych hazardach spróbujemy
rozwiązać za pomocą warstwowania względem zmiennej \texttt{COND}, gdyż
ona według wyniku testu Schoenfelda miała najgorszy wynik. Poniżej
wykres przedstawiający wykres skumulowanego hazardu dla wartości każdego
z poziomów \texttt{COND} (model proporcjonalnych hazardów, to również
model proporcjonalnych skumulowanych hazardów). Krzywe sie przecinają i
wykres również wskazuje na niespełnienie ząłożeń proporcjonalnych
hazardów w przypadku zmiennej \texttt{COND}.

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-25-1.pdf}

Spróbujemy zatem dopasować model z tymi samymi zmiennymi, jednak
dokonując warstwowania według zmiennej \texttt{COND}.

\begin{longtable}[]{@{}lrrrrr@{}}
\toprule
& coef & exp(coef) & se(coef) & z &
Pr(\textgreater\textbar z\textbar) \\
\midrule
\endhead
SEX2 & -0.3560255 & 0.7004548 & 0.2127088 & -1.6737697 & 0.0941759 \\
T\_STAGE3 & -0.0447717 & 0.9562157 & 0.2565739 & -0.1744983 &
0.8614738 \\
T\_STAGE4 & 0.5534027 & 1.7391607 & 0.2601873 & 2.1269396 & 0.0334251 \\
\bottomrule
\end{longtable}

Według testu Walda obie zmienne \texttt{T\_STAGE} oraz \texttt{SEX} po
przeprowadzeniu warstwowania są istotne. Sprawdzimy czy dla tak
powstałego modelu założenia proporcjonalnych hazardów są spełnione,
ponownie za pomocą testu Schoenfelda: chisq df p SEX 0.279 1 0.60
T\_STAGE 1.857 2 0.40 GLOBAL 2.110 3 0.55

\begin{longtable}[]{@{}lrrr@{}}
\toprule
& chisq & df & p \\
\midrule
\endhead
SEX & 0.2792625 & 1 & 0.5971850 \\
T\_STAGE & 1.8573835 & 2 & 0.3950702 \\
GLOBAL & 2.1102079 & 3 & 0.5498504 \\
\bottomrule
\end{longtable}

Duże wartości p-value nie odrzuca nam hipotezy zerowej o spełnieniu
założenia proporcjonalności hazardów dla każdej ze zmiennych.

Dla nowo powstałego modelu również przeprowadzaona została diagnostyka
mająca na celu wyłapanie potencjalnych obserwacji odstających lub
wpływowych, lecz takie nie zostały znalezione.

Ostateczna postać modelu to: \[
\lambda(t) = \lambda_{i}(t)\cdot \exp(-0.356 \cdot X_{sex2} - 0.045 \cdot X_{t_stage3} + 0.553 \cdot X_{t_stage4})
\] dla \(i = 1, 2, 3\), gdzie \(\lambda_{i}(t)\) to hazard bazowy dla
i-tego poziomu zmiennej \texttt{COND}.

\hypertarget{model-atf}{%
\section{Model ATF}\label{model-atf}}

W ostatnim etapie analizy do danych zostanie dopasowany model AFT (ang.
accelerated failure time), czyli model przyspieszonego czasu do
niepowodzenia.

\hypertarget{dopasowanie-modelu}{%
\subsubsection{Dopasowanie modelu}\label{dopasowanie-modelu}}

w pierwszej kolejności do danych został dopasowany rozład uogólniony
gamma w celu sprawdzenia, czy któryś rozkład z tej rodizny rozkładów
będzie odpowiedni dla naszych dnaych. Wyboru zmiennych dokonujemy za
pomocą kryterium AIC. Wybrane zmienne to: \texttt{T\_STAGE},
\texttt{SEX} oraz \texttt{COND}, czyli te same zmienne co w przypadku
modelu Coxa.

Sprawdzamy przedział ufności dla parametru \(Q\) aby sprawdzić czy
zawiera on \(1\) (rozkład Weibulla) lub \(0\) (rozkład log normalny).

\begin{longtable}[]{@{}lr@{}}
\toprule
& x \\
\midrule
\endhead
2.5 \% & -0.8233599 \\
97.5 \% & 0.2036972 \\
\bottomrule
\end{longtable}

Przedział nie zawiera ani \(1\) ani \(0\). Dla pewności dopasowany
został osobno również rozkład Wiebulla, jako że jest to najbardziej
popularny rozkład dla modeli AFT. Jednak wykresy diagnostyczne
potwierdzają złe dopasowanie rozkładu do do danych.

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-32-1.pdf}

Wykres sugeruje, że rozkład Weibulla nie jest dobrym wyborem dla naszych
danych.

Spróbujmy dopasować model dla rozkładu log-logistic.

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-34-1.pdf}

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-35-1.pdf}

Lepsze dopasowanie.

\hypertarget{obserwacje-odstajace-dla-modelu-logistic}{%
\subsubsection{Obserwacje odstajace dla modelu
logistic}\label{obserwacje-odstajace-dla-modelu-logistic}}

\includegraphics{Anna_Herud-Projekt5_files/figure-latex/unnamed-chunk-36-1.pdf}

Ostateczna postać modelu: \[
log(T) = 6.76 -0.98\cdot X_{cond2} - 1.28\cdot X_{cond3} - 0.05\cdot X_{t_stage3} - 0.54\cdot X_{t_stage4}+ 0.05 \cdot X_{n_stage2} - 0.31 \cdot X_{n_stage4}+0.53 \varepsilon
\]

\hypertarget{podsumowanie}{%
\section{Podsumowanie}\label{podsumowanie}}

Przeprowadzona powyżej analiza danych pacjentów cierpiących na raka
części ustnej gardła pozwoliła na wysnucie następujących wniosków:

\begin{itemize}
\item
  Zmienna określająca wielkość guza (\texttt{T\_STAGE}) to zmienna,
  która we wszystkich trzech punktach analizy wykazała wpływ na
  prawdopodobieństwo przeżycia pacjenta. Wynik ten jest intuicyjny,
  wielkość guza świadczy o powadze stanu pacjenta.
\item
  Pozostałe zmienne, które wykazały wpływ na prawdopodobieństwo
  przeżycia, na przynajmniej jednym z etapów analizy to: liczba węzłów z
  przerzutami (\texttt{N\_STAGE}), sprawność pacjenta (\texttt{COND})
  oraz płeć.
\item
  Powstały model Coxa pozwala nam na następująca interpretacje wpływu
  płci oraz wielkości guza (dla każdego stopnia sprawności pacjenta
  osobno):

  \begin{itemize}
  \item
    dla płci żeńskiej hazard jest 0.7 razy niższy niż dla płci męskiej
    (\(HR_{sex2} = exp(-0.356)\))
  \item
    dla guzów większych niż 3 cm hazard jest 0.95 niższy niż dla
    pozostałych grup zmiennej (\(HR_{t_stage3} = exp(-0.045)\))
  \item
    dla masywnych guzów z naciekiem na okoliczne tkanki hazard jest 1.74
    razy wyższy niż w pozostałych grupach
    (\(HR_{t_stage4} = exp(0.553)\)).
  \end{itemize}
\item
  Powstały model AFT pozwala nam na następującą interpretację wpływu
  zmiennych określających płeć, sprawność pacjenta oraz wielkość guzu:

  \begin{itemize}
  \tightlist
  \item
  \item
  \item
  \end{itemize}
\end{itemize}

\end{document}
